### ISSUE TITLE
erro launching

### ISSUE THREAD

**Issue by paulossant** [Nikolaos-MAtthaiakakis/MNPBEM_GUI#1]
When trying to launch the program i face the following error:
```
Error using nargout
Error: File: MNPBEM_GUI.mlapp Line: 5 Column: 47
Unexpected MATLAB operator.

Error in MNPBEM_GUIApp/startApp (line 58)
        if nargout(@MNPBEM_GUI) == 0

Error in MNPBEM_GUIApp (line 38)
      startApp(obj)

Error in appinstall.internal.runapp>execute (line 79)
out = evalin('caller', [script ';']);

Error in appinstall.internal.runapp1runapp13a (line 58)
outobj = execute(fullfile(appinstalldir, [wrapperfile 'App.m']));

Error in appinstall.internal.runapp>runcorrectversion (line 35)
    appobj = runapp13a(appinstalldir);

Error in appinstall.internal.runapp (line 17)
        out = runcorrectversion(appmetadata, appentrypoint, appinstalldir);
```

I have changed the folder name accordingle and sucessfully installed the app, but cannot launch it either from inside the matlab or from the system explorer folder.

any help?
best regards,
Paulo

**Comment by Nikolaos-Matthaiakakis** [comment]
Hello, I haven't seen this error before. Have you tried running it without installing the app? You can directly run the code by opening the MNPBEM_GUI.mlapp file instead. This should be the safest way to test if it works.

Best wishes
Nikolaos

**Comment by paulossant** [comment]
launching directly from .mlapp does not work either. I am running matlab2015, could it be something related to it?

**Comment by Nikolaos-Matthaiakakis** [comment]
Yes, this is based on matlab app designer and I believe the 2015 version doesn't yet support it. You can still use the base MNPBEM toolbox in the form of code of course.

https://physik.uni-graz.at/de/mnpbem/ 

or the newer  nanobem which also better handles dielectric particles

https://arxiv.org/abs/2203.03283

https://github.com/uhohenester/nanobem22

**Comment by paulossant** [comment]
Thank you! I will check the nanobem toolbox.

best regards
